# configuration for https://github.com/sagiegurari/cargo-make

[config]
skip_core_tasks = true

[env]
# all features except the backend ones
ALL_FEATURES = "all-widgets,macros,serde"

# Windows does not support building termion, so this avoids the build failure by providing two
# sets of flags, one for Windows and one for other platforms.
# Windows: --features=all-widgets,macros,serde,crossterm,termwiz
# Other: --all-features
ALL_FEATURES_FLAG = { source = "${CARGO_MAKE_RUST_TARGET_OS}", default_value = "--all-features", mapping = { "windows" = "--features=all-widgets,macros,serde,crossterm,termwiz" } }

[tasks.default]
alias = "ci"

[tasks.ci]
description = "Run continuous integration tasks"
dependencies = ["lint-style", "clippy", "check", "test"]

[tasks.lint-style]
description = "Lint code style (formatting, typos, docs)"
dependencies = ["lint-format", "lint-typos", "lint-docs"]

[tasks.lint-format]
description = "Lint code formatting"
toolchain = "nightly"
command = "cargo"
args = ["fmt", "--all", "--check"]

[tasks.format]
description = "Fix code formatting"
toolchain = "nightly"
command = "cargo"
args = ["fmt", "--all"]

[tasks.lint-typos]
description = "Run typo checks"
install_crate = { crate_name = "typos-cli", binary = "typos", test_arg = "--version" }
command = "typos"

[tasks.lint-docs]
description = "Check documentation for errors and warnings"
toolchain = "nightly"
command = "cargo"
args = [
  "rustdoc",
  "--",
  "-Zunstable-options",
  "--check",
  "-Dwarnings",
]

[tasks.check]
description = "Check code for errors and warnings"
command = "cargo"
args = [
  "check",
  "--all-targets",
]

[tasks.build]
description = "Compile the project"
command = "cargo"
args = [
  "build",
  "--all-targets",
]

[tasks.clippy]
description = "Run Clippy for linting"
command = "cargo"
args = [
  "clippy",
  "--all-targets",
  "--tests",
  "--benches",
  "--",
  "-D",
  "warnings",
]

[tasks.test]
description = "Run tests"
dependencies = ["test-doc"]
command = "cargo"
args = [
  "test",
  "--all-targets",
  "--locked", 
  "--all-features"
]

[tasks.test-doc]
description = "Run documentation tests"
command = "cargo"
args = ["test", "--doc", "--no-default-features"]

[tasks.coverage]
description = "Generate code coverage report"
command = "cargo"
args = [
  "llvm-cov",
  "--lcov",
  "--output-path",
  "target/lcov.info",
  "--no-default-features",
  "${ALL_FEATURES_FLAG}",
]
