Output "gifs/complete.gif"
Set Theme "OceanicMaterial"
Set FontSize 12
Set Width 824
Set Height 600
Show
Type "cat real_curl_example.yaml"
Enter
Sleep 300ms
Type "logss -f real_curl_example.yaml"
Enter
Sleep 500ms
# Showcase Inputs
Type "i"
Type@200ms "image"
Enter
# Showcase VerticalView
Type "v"
Sleep 1s
Type "v"
Sleep 1s
# Showcase Single
Type "s"
Sleep 2s
Type "s"
Sleep 1s
# Showcase Barchart
Type "b"
Sleep 2s
Type "b"
Sleep 1s
